development:
  adapter: postgresql
  encoding: unicode
  database: qaror-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: qaror-test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: qaror-prod
  pool: 5
  host: localhost
  username: action
  password: